name = "generative-adventure"
main = "src/index.js"
compatibility_date = "2023-10-30"

[site]
bucket = "./public"

[[r2_buckets]]
binding = "STORY_STORAGE"
bucket_name = "generative-adventure-storage"
preview_bucket_name = "generative-adventure-storage-preview"
